# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import exchange_rates_pb2 as exchange__rates__pb2


class ExchangeRatesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAmount = channel.unary_unary(
                '/exchange_rates.ExchangeRatesService/GetAmount',
                request_serializer=exchange__rates__pb2.GetAmountRequest.SerializeToString,
                response_deserializer=exchange__rates__pb2.GetAmountResponse.FromString,
                )


class ExchangeRatesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAmount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ExchangeRatesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAmount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAmount,
                    request_deserializer=exchange__rates__pb2.GetAmountRequest.FromString,
                    response_serializer=exchange__rates__pb2.GetAmountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exchange_rates.ExchangeRatesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ExchangeRatesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAmount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/exchange_rates.ExchangeRatesService/GetAmount',
            exchange__rates__pb2.GetAmountRequest.SerializeToString,
            exchange__rates__pb2.GetAmountResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
