# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_rates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange_rates.proto',
  package='exchange_rates',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x65xchange_rates.proto\x12\x0e\x65xchange_rates\"E\n\x10GetAmountRequest\x12\x0c\n\x04\x62\x61se\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x01\"#\n\x11GetAmountResponse\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x01\x32h\n\x14\x45xchangeRatesService\x12P\n\tGetAmount\x12 .exchange_rates.GetAmountRequest\x1a!.exchange_rates.GetAmountResponseb\x06proto3'
)




_GETAMOUNTREQUEST = _descriptor.Descriptor(
  name='GetAmountRequest',
  full_name='exchange_rates.GetAmountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='base', full_name='exchange_rates.GetAmountRequest.base', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='destination', full_name='exchange_rates.GetAmountRequest.destination', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='exchange_rates.GetAmountRequest.amount', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=109,
)


_GETAMOUNTRESPONSE = _descriptor.Descriptor(
  name='GetAmountResponse',
  full_name='exchange_rates.GetAmountResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='amount', full_name='exchange_rates.GetAmountResponse.amount', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['GetAmountRequest'] = _GETAMOUNTREQUEST
DESCRIPTOR.message_types_by_name['GetAmountResponse'] = _GETAMOUNTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetAmountRequest = _reflection.GeneratedProtocolMessageType('GetAmountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETAMOUNTREQUEST,
  '__module__' : 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:exchange_rates.GetAmountRequest)
  })
_sym_db.RegisterMessage(GetAmountRequest)

GetAmountResponse = _reflection.GeneratedProtocolMessageType('GetAmountResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETAMOUNTRESPONSE,
  '__module__' : 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:exchange_rates.GetAmountResponse)
  })
_sym_db.RegisterMessage(GetAmountResponse)



_EXCHANGERATESSERVICE = _descriptor.ServiceDescriptor(
  name='ExchangeRatesService',
  full_name='exchange_rates.ExchangeRatesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAmount',
    full_name='exchange_rates.ExchangeRatesService.GetAmount',
    index=0,
    containing_service=None,
    input_type=_GETAMOUNTREQUEST,
    output_type=_GETAMOUNTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGERATESSERVICE)

DESCRIPTOR.services_by_name['ExchangeRatesService'] = _EXCHANGERATESSERVICE

# @@protoc_insertion_point(module_scope)
