# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import payments_pb2 as payments__pb2


class PaymentsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetReceiptById = channel.unary_unary(
                '/payments.PaymentsService/GetReceiptById',
                request_serializer=payments__pb2.GetReceiptForOrderRequest.SerializeToString,
                response_deserializer=payments__pb2.GetReceiptForOrderResponse.FromString,
                )


class PaymentsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetReceiptById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaymentsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetReceiptById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReceiptById,
                    request_deserializer=payments__pb2.GetReceiptForOrderRequest.FromString,
                    response_serializer=payments__pb2.GetReceiptForOrderResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'payments.PaymentsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PaymentsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetReceiptById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/payments.PaymentsService/GetReceiptById',
            payments__pb2.GetReceiptForOrderRequest.SerializeToString,
            payments__pb2.GetReceiptForOrderResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
