export const IDENTITY_PROVIDER_DOMAIN = process.env
  .REACT_APP_IDENTITY_PROVIDER_DOMAIN as string;
export const IDENTITY_PROVIDER_CLIENT_ID = process.env
  .REACT_APP_IDENTITY_PROVIDER_CLIENT_ID as string;
export const IDENTITY_PROVIDER_SCOPE = process.env
  .REACT_APP_IDENTITY_PROVIDER_SCOPE as string;
